name: Test
on:
  pull_request:
    types:
      - opened
      - reopened
  workflow_dispatch:
  push:
    branches:
      - main
      - 'dev-*'    # any branch with name such as dev-new, dev-new-test
      - 'feat/**'  # any feature branches such as feat/new, feat/new/pr
    paths-ignore:
      - 'github/workflows/*'  # workflow will not run for any files changes in workflow

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: set up jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'
          cache: maven
      - name: Install Dependencies
        run: mvn clean compile
  test:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: set up jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'
          cache: maven
      - name: run test
        run: mvn test
  done:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: | 
            echo "This job was triggered by ${{github.event_name}} event."
            echo "🍏 This job's status is ${{ job.status }}."


