name: Test
on:
  pull_request:
    types:
      - opened
      - reopened
  workflow_dispatch:
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: set up jdk 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'corretto'
          cache: maven
      - name: Install Dependencies
        run: mvn clean compile
  test:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: set up jdk 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'corretto'
          cache: maven
      - name: run test
        run: mvn test
  done:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: | 
            echo "This job was triggered by {{github.event_name}} event."
            echo "🍏 This job's status is ${{ job.status }}."


